// Sparse, nature-led soundscape (brief §9). Off by default; one button toggles everything with a ~0.5 s fade.
// Files live in /audio/; audio/manifest.json (generated by vite.config.js) says which exist, and missing layers are skipped.

const rand = (a, b) => a + Math.random() * (b - a);

const LAYERS = {
  bed: 'bed-wind-leaves.mp3',
  music: 'music.mp3',
  birds: ['bird-01.mp3', 'bird-02.mp3', 'bird-03.mp3', 'bird-04.mp3', 'bird-05.mp3', 'bird-06.mp3'],
  creaks: ['creak-01.mp3', 'creak-02.mp3', 'creak-03.mp3', 'creak-04.mp3'],
  bell: 'bell.mp3',
};

export class Soundscape {
  constructor(base) {
    this.base = base;
    this.on = false;
    this.ctx = null;
    this.buffers = {};
    this.timers = [];
    this.lastBell = -1e9;
  }

  async load(name) {
    if (this.available && !this.available.has(name)) return null;
    try {
      const res = await fetch(this.base + name);
      if (!res.ok) return null;
      return await this.ctx.decodeAudioData(await res.arrayBuffer());
    } catch { return null; }
  }

  async init() {
    const Ctx = window.AudioContext || window.webkitAudioContext;
    this.ctx = new Ctx();
    this.master = this.ctx.createGain();
    this.master.gain.value = 0;
    this.master.connect(this.ctx.destination);
    try {
      const res = await fetch(this.base + 'manifest.json');
      if (res.ok) this.available = new Set(await res.json());
    } catch { /* no manifest: try every file */ }

    // the bed first, so sound starts quickly; everything else follows
    this.buffers.bed = await this.load(LAYERS.bed);
    if (this.buffers.bed) {
      const src = this.ctx.createBufferSource();
      src.buffer = this.buffers.bed; src.loop = true;
      const g = this.ctx.createGain(); g.gain.value = 0.8;       // the loudest layer
      src.connect(g).connect(this.master); src.start();
    }
    this.loadRest();   // not awaited: the bed plays while music and one-shots decode
  }

  async loadRest() {
    const [music, bell, birds, creaks] = await Promise.all([
      this.load(LAYERS.music), this.load(LAYERS.bell),
      Promise.all(LAYERS.birds.map((f) => this.load(f))),
      Promise.all(LAYERS.creaks.map((f) => this.load(f))),
    ]);
    Object.assign(this.buffers, { music, bell, birds: birds.filter(Boolean), creaks: creaks.filter(Boolean) });

    if (music) this.startMusic();
    this.loop(() => rand(20, 60), () => this.oneShot(this.buffers.birds, 0.4, rand(-0.8, 0.8), rand(0.92, 1.08)));
    this.loop(() => rand(60, 120), () => this.oneShot(this.buffers.creaks, 0.3, rand(-0.4, 0.4), rand(0.95, 1.05)));
    this.loop(() => rand(240, 480), () => this.ringBell());
  }

  // Music sits well under the bed and breathes: fade in over a minute, hold, fade out, rest.
  startMusic() {
    const src = this.ctx.createBufferSource();
    src.buffer = this.buffers.music; src.loop = true;
    const g = this.ctx.createGain(); g.gain.value = 0;
    src.connect(g).connect(this.master); src.start();
    const LEVEL = 0.14;
    const cycle = () => {
      const t = this.ctx.currentTime, fadeIn = 60, hold = rand(90, 150), fadeOut = 60, rest = rand(60, 120);
      g.gain.cancelScheduledValues(t);
      g.gain.setValueAtTime(g.gain.value, t);
      g.gain.linearRampToValueAtTime(LEVEL, t + fadeIn);
      g.gain.setValueAtTime(LEVEL, t + fadeIn + hold);
      g.gain.linearRampToValueAtTime(0, t + fadeIn + hold + fadeOut);
      this.timers.push(setTimeout(cycle, (fadeIn + hold + fadeOut + rest) * 1000));
    };
    cycle();
  }

  oneShot(list, gain, pan, rate) {
    if (!this.on || !list || !list.length) return;
    const buf = Array.isArray(list) ? list[Math.floor(Math.random() * list.length)] : list;
    const src = this.ctx.createBufferSource();
    src.buffer = buf; src.playbackRate.value = rate;
    const g = this.ctx.createGain(); g.gain.value = gain;
    const p = this.ctx.createStereoPanner ? this.ctx.createStereoPanner() : null;
    if (p) { p.pan.value = pan; src.connect(g).connect(p).connect(this.master); } else src.connect(g).connect(this.master);
    src.start();
  }

  ringBell() {
    if (!this.buffers.bell || !this.on) return;
    const now = performance.now();
    if (now - this.lastBell < 45000) return;
    this.lastBell = now;
    this.oneShot([this.buffers.bell], 0.35, rand(-0.2, 0.2), 1);
  }

  loop(delay, fn) {
    const tick = () => { fn(); this.timers.push(setTimeout(tick, delay() * 1000)); };
    this.timers.push(setTimeout(tick, delay() * 1000));
  }

  onPov() { if (this.on) this.ringBell(); }

  async toggle() {
    this.on = !this.on;
    if (!this.ctx) await this.init();
    if (this.on && this.ctx.state === 'suspended') await this.ctx.resume();
    const t = this.ctx.currentTime;
    this.master.gain.cancelScheduledValues(t);
    this.master.gain.setValueAtTime(this.master.gain.value, t);
    this.master.gain.linearRampToValueAtTime(this.on ? 1 : 0, t + 0.5);
    if (!this.on) {
      const ctx = this.ctx;
      setTimeout(() => { if (!this.on) ctx.suspend(); }, 600);
    }
    return this.on;
  }
}
